### ISSUE TITLE
Postgres Connection through Bastion Host

### ISSUE THREAD

**Issue by ktham** [terraform-providers/terraform-provider-postgresql#62] opened 2019-02-08 00:54 UTC
I'd like to use the Postgres TF provider on Terraform Enterprise, however, our database is in a private network and is not publicly visible. I'd like to configure the pg connection to go through a bastion host.

Can we add the ability to specify a bastion host as a proxy node? I can also try to contribute if this is a feature that can be incorporated into this provider.

**Comment by cyrilgdn** [comment] 2019-02-08 10:43
Hi @ktham, I allow myself to close this issue as it seems to be a duplicate of #42. Feel free to open it back if I missed something.

As a new maintainer of this provider, for now I'm focus on releasing new versions with all the stuff that have already been done. So I didn't get time to think about this problem yet.

If you have some ideas, you can share it on the #42 issue ! And if you want to give a try and to contribute you're more than welcome :) (but It's important to talk about your solution in the issue before implementing it so people can help).

**Closed by cyrilgdn** 2019-02-08 10:43 UTC
